### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FeodorFitsner** [nickvdyck/webtty#6]
Hi Nick,

Great work! Would you mind adding a license to this project, so people could use webtty tool and contribute into it? Thank you!

**Comment by FeodorFitsner** [comment]
Thank you for adding the license!

**Comment by nickvdyck** [comment]
Sr for the late reply had a busy couple of days.

Thanks for bringing this to my attention, I never really considered other people using or contributing. This was more of a personal playground and an opportunity to learn new development areas.

Anyways I added an MIT license to the project.  😄
